// <auto-generated />
using System;
using AgendaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgendaApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260324110533_AgregarVeinteUsuarios")]
    partial class AgregarVeinteUsuarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgendaApi.Models.Agenda", b =>
                {
                    b.Property<string>("Id_usuario")
                        .HasColumnType("text");

                    b.Property<int>("Id_evento")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id_usuario", "Id_evento");

                    b.HasIndex("Id_evento");

                    b.ToTable("Agendas", (string)null);

                    b.HasData(
                        new
                        {
                            Id_usuario = "u-lizeth-60171101",
                            Id_evento = 1,
                            Estado = "Aceptado",
                            FechaAsignacion = new DateTime(2026, 3, 24, 11, 5, 26, 489, DateTimeKind.Utc).AddTicks(2015)
                        },
                        new
                        {
                            Id_usuario = "u-lizeth-60171101",
                            Id_evento = 2,
                            Estado = "Pendiente",
                            FechaAsignacion = new DateTime(2026, 3, 24, 11, 5, 26, 489, DateTimeKind.Utc).AddTicks(5038)
                        },
                        new
                        {
                            Id_usuario = "u-eddy-67015593",
                            Id_evento = 3,
                            Estado = "Aceptado",
                            FechaAsignacion = new DateTime(2026, 3, 24, 11, 5, 26, 489, DateTimeKind.Utc).AddTicks(5041)
                        },
                        new
                        {
                            Id_usuario = "u-eddy-67015593",
                            Id_evento = 4,
                            Estado = "Pendiente",
                            FechaAsignacion = new DateTime(2026, 3, 24, 11, 5, 26, 489, DateTimeKind.Utc).AddTicks(5043)
                        });
                });

            modelBuilder.Entity("AgendaApi.Models.Evento", b =>
                {
                    b.Property<int>("Id_evento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_evento"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha_finalizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fecha_inicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Hora_finalizacion")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("Hora_inicio")
                        .HasColumnType("interval");

                    b.Property<string>("Id_usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Imagen")
                        .HasColumnType("text");

                    b.Property<double>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_evento");

                    b.HasIndex("Id_usuario");

                    b.ToTable("Eventos", (string)null);

                    b.HasData(
                        new
                        {
                            Id_evento = 1,
                            Descripcion = "",
                            Fecha_finalizacion = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fecha_inicio = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hora_finalizacion = new TimeSpan(0, 11, 0, 0, 0),
                            Hora_inicio = new TimeSpan(0, 9, 0, 0, 0),
                            Id_usuario = "u-eddy-67015593",
                            Latitud = 0.0,
                            Longitud = 0.0,
                            Lugar = "Oficina Central",
                            Nombre = "Reunión de Proyecto IATEC",
                            Tipo = "Compartido"
                        },
                        new
                        {
                            Id_evento = 2,
                            Descripcion = "",
                            Fecha_finalizacion = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fecha_inicio = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hora_finalizacion = new TimeSpan(0, 21, 0, 0, 0),
                            Hora_inicio = new TimeSpan(0, 19, 0, 0, 0),
                            Id_usuario = "u-eddy-67015593",
                            Latitud = 0.0,
                            Longitud = 0.0,
                            Lugar = "Cancha 5",
                            Nombre = "Partido de Futbol",
                            Tipo = "Exclusivo"
                        },
                        new
                        {
                            Id_evento = 3,
                            Descripcion = "",
                            Fecha_finalizacion = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fecha_inicio = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hora_finalizacion = new TimeSpan(0, 16, 0, 0, 0),
                            Hora_inicio = new TimeSpan(0, 14, 0, 0, 0),
                            Id_usuario = "u-lizeth-60171101",
                            Latitud = 0.0,
                            Longitud = 0.0,
                            Lugar = "Auditorio",
                            Nombre = "Presentación de Tesis",
                            Tipo = "Compartido"
                        },
                        new
                        {
                            Id_evento = 4,
                            Descripcion = "",
                            Fecha_finalizacion = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fecha_inicio = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hora_finalizacion = new TimeSpan(0, 11, 0, 0, 0),
                            Hora_inicio = new TimeSpan(0, 10, 0, 0, 0),
                            Id_usuario = "u-lizeth-60171101",
                            Latitud = 0.0,
                            Longitud = 0.0,
                            Lugar = "Clínica Dental",
                            Nombre = "Cita Dental",
                            Tipo = "Exclusivo"
                        });
                });

            modelBuilder.Entity("AgendaApi.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Ape_materno")
                        .HasColumnType("text");

                    b.Property<string>("Ape_paterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fecha_naci")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Foto_perfil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "u-eddy-67015593",
                            AccessFailedCount = 0,
                            Ape_materno = "Condori",
                            Ape_paterno = "Mamani",
                            ConcurrencyStamp = "6f804301-561f-448d-83e4-ba606dfb1b85",
                            Email = "eddy@test.com",
                            EmailConfirmed = true,
                            FechaRegistro = new DateTime(2026, 3, 24, 11, 5, 26, 509, DateTimeKind.Utc).AddTicks(4963),
                            Fecha_naci = new DateTime(1995, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Foto_perfil = "/images/user-default.png",
                            LockoutEnabled = false,
                            Nombre = "Eddy",
                            NormalizedEmail = "EDDY@TEST.COM",
                            NormalizedUserName = "EDDY@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECvcG3A72ek3trb+xWV1KJ+EniIA14r2j7iSs66Pyn35/4zDqp2PVBc91JFDD/Se3A==",
                            PhoneNumber = "67015593",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "474c501d-c9f9-4f27-9343-0495286c44eb",
                            TwoFactorEnabled = false,
                            UserName = "eddy@test.com"
                        },
                        new
                        {
                            Id = "u-lizeth-60171101",
                            AccessFailedCount = 0,
                            Ape_materno = "Fernandez",
                            Ape_paterno = "Calle",
                            ConcurrencyStamp = "df58e7b6-0849-424d-b700-98da040c130b",
                            Email = "lizeth@test.com",
                            EmailConfirmed = true,
                            FechaRegistro = new DateTime(2026, 3, 24, 11, 5, 26, 840, DateTimeKind.Utc).AddTicks(4351),
                            Fecha_naci = new DateTime(1998, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Foto_perfil = "/images/user-default.png",
                            LockoutEnabled = false,
                            Nombre = "Lizeth Aidee",
                            NormalizedEmail = "LIZETH@TEST.COM",
                            NormalizedUserName = "LIZETH@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELAes86yvvN3GIN51Un29QFaWlxWwqZYK/vd9RTpJccTIFKlgM9bmHu8iPxVupRqVg==",
                            PhoneNumber = "60171101",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0eb06871-04a4-470d-bc3f-4b13626074f2",
                            TwoFactorEnabled = false,
                            UserName = "lizeth@test.com"
                        },
                        new
                        {
                            Id = "u-juan-1001",
                            AccessFailedCount = 0,
                            Ape_materno = "Lopez",
                            Ape_paterno = "Perez",
                            ConcurrencyStamp = "685d4753-e92c-4573-8b1d-38d328db8179",
                            Email = "juan@test.com",
                            EmailConfirmed = true,
                            FechaRegistro = new DateTime(2026, 3, 24, 11, 5, 27, 87, DateTimeKind.Utc).AddTicks(2880),
                            Fecha_naci = new DateTime(1990, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Foto_perfil = "/images/user-default.png",
                            LockoutEnabled = false,
                            Nombre = "Juan",
                            NormalizedEmail = "JUAN@TEST.COM",
                            NormalizedUserName = "JUAN@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPi3sz9uie7lMwNgr6vJ0Zoz+zDsD1cuv1hmWnLuanM0zuR4x6qppsnzWCsOMlkUvw==",
                            PhoneNumber = "71234561",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "18d11623-1f8b-49ce-b697-831ed40f37ea",
                            TwoFactorEnabled = false,
                            UserName = "juan@test.com"
                        },
                        new
                        {
                            Id = "u-maria-1002",
                            AccessFailedCount = 0,
                            Ape_materno = "Sosa",
                            Ape_paterno = "Gomez",
                            ConcurrencyStamp = "a62dd9f8-6173-43ff-8afe-54cc3b1fc539",
                            Email = "maria@test.com",
                            EmailConfirmed = true,
                            FechaRegistro = new DateTime(2026, 3, 24, 11, 5, 27, 269, DateTimeKind.Utc).AddTicks(8138),
                            Fecha_naci = new DateTime(1992, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Foto_perfil = "/images/user-default.png",
                            LockoutEnabled = false,
                            Nombre = "Maria",
                            NormalizedEmail = "MARIA@TEST.COM",
                            NormalizedUserName = "MARIA@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEfnnyTQQ2s/ldA9F/eTxq2Q6gQH0lw1j5PM07tJjL1i3J3qUOpFpG457xkbwRHO8g==",
                            PhoneNumber = "71234562",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0d04e3f0-5ddb-4587-b397-4cec033f21c4",
                            TwoFactorEnabled = false,
                            UserName = "maria@test.com"
                        },
                        new
                        {
                            Id = "u-carlos-1003",
                            AccessFailedCount = 0,
                            Ape_materno = "Vargas",
                            Ape_paterno = "Rodriguez",
                            ConcurrencyStamp = "491a6083-e8ad-4f5e-97ba-1f5715333a2d",
                            Email = "carlos@test.com",
                            EmailConfirmed = true,
                            FechaRegistro = new DateTime(2026, 3, 24, 11, 5, 27, 453, DateTimeKind.Utc).AddTicks(2650),
                            Fecha_naci = new DateTime(1988, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Foto_perfil = "/images/user-default.png",
                            LockoutEnabled = false,
                            Nombre = "Carlos",
                            NormalizedEmail = "CARLOS@TEST.COM",
                            NormalizedUserName = "CARLOS@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBbd2SWJL+a8/5CSmyYR0naI9h6fmylOJUKRNDf3midsUI6P/eW2mP/XHcRUYdMdyw==",
                            PhoneNumber = "71234563",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "af571ab6-3197-45db-90ec-7b3e91a18e29",
                            TwoFactorEnabled = false,
                            UserName = "carlos@test.com"
                        },
                        new
                        {
                            Id = "u-ana-1004",
                            AccessFailedCount = 0,
                            Ape_materno = "Flores",
                            Ape_paterno = "Martinez",
                            ConcurrencyStamp = "febf1d6a-83c8-45d9-a13c-1cea3eb2f13a",
                            Email = "ana@test.com",
                            EmailConfirmed = true,
                            FechaRegistro = new DateTime(2026, 3, 24, 11, 5, 27, 663, DateTimeKind.Utc).AddTicks(9548),
                            Fecha_naci = new DateTime(1994, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Foto_perfil = "/images/user-default.png",
                            LockoutEnabled = false,
                            Nombre = "Ana",
                            NormalizedEmail = "ANA@TEST.COM",
                            NormalizedUserName = "ANA@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENAmrgek/BN5PjlLlewM1dgRTxec06/BuSOqSrBoFFT+L1KaqarLv6IuhhWYqkjQsQ==",
                            PhoneNumber = "71234564",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "14643eb0-52c3-4f5a-81e4-4e126dce759c",
                            TwoFactorEnabled = false,
                            UserName = "ana@test.com"
                        },
                        new
                        {
                            Id = "u-pedro-1005",
                            AccessFailedCount = 0,
                            Ape_materno = "Ramos",
                            Ape_paterno = "Sanchez",
                            ConcurrencyStamp = "51ad3a41-e670-4db1-9b00-3dfabc2cf3f5",
                            Email = "pedro@test.com",
                            EmailConfirmed = true,
                            FechaRegistro = new DateTime(2026, 3, 24, 11, 5, 27, 871, DateTimeKind.Utc).AddTicks(324),
                            Fecha_naci = new DateTime(1985, 12, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Foto_perfil = "/images/user-default.png",
                            LockoutEnabled = false,
                            Nombre = "Pedro",
                            NormalizedEmail = "PEDRO@TEST.COM",
                            NormalizedUserName = "PEDRO@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOQWJgLvft4o+kQcXTM8EQIcqa91vs7OF+w7YVpq76G3108q2pHxkg0pu03J8RSHtg==",
                            PhoneNumber = "71234565",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6a5c16de-5d7b-4050-ab28-915c6aabc379",
                            TwoFactorEnabled = false,
                            UserName = "pedro@test.com"
                        },
                        new
                        {
                            Id = "u-lucia-1006",
                            AccessFailedCount = 0,
                            Ape_materno = "Torres",
                            Ape_paterno = "Diaz",
                            ConcurrencyStamp = "ff09df98-fae0-40ea-8ff9-de1c9535fe9a",
                            Email = "lucia@test.com",
                            EmailConfirmed = true,
                            FechaRegistro = new DateTime(2026, 3, 24, 11, 5, 28, 109, DateTimeKind.Utc).AddTicks(824),
                            Fecha_naci = new DateTime(1997, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Foto_perfil = "/images/user-default.png",
                            LockoutEnabled = false,
                            Nombre = "Lucia",
                            NormalizedEmail = "LUCIA@TEST.COM",
                            NormalizedUserName = "LUCIA@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECTGphNE6G2zqCdxzznfUmL/Fgt7/Ks08OhcfitbgxYqkkvaJlIY7sVY1JfBBwlecQ==",
                            PhoneNumber = "71234566",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b6b556cd-608d-4950-b604-e11ec2c252bf",
                            TwoFactorEnabled = false,
                            UserName = "lucia@test.com"
                        },
                        new
                        {
                            Id = "u-jorge-1007",
                            AccessFailedCount = 0,
                            Ape_materno = "Morales",
                            Ape_paterno = "Ruiz",
                            ConcurrencyStamp = "10e3f5a3-942c-4611-849b-b33e995003ce",
                            Email = "jorge@test.com",
                            EmailConfirmed = true,
                            FechaRegistro = new DateTime(2026, 3, 24, 11, 5, 28, 274, DateTimeKind.Utc).AddTicks(3162),
                            Fecha_naci = new DateTime(1991, 6, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Foto_perfil = "/images/user-default.png",
                            LockoutEnabled = false,
                            Nombre = "Jorge",
                            NormalizedEmail = "JORGE@TEST.COM",
                            NormalizedUserName = "JORGE@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELhlnHtBNE7oJ4o8DhE2MS7rKJkUe0drXjXhvzfWNS7TMbXLFKrwgi1szwoVenS34g==",
                            PhoneNumber = "71234567",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5870c3d4-84c5-4bfe-af27-91c80a436e2c",
                            TwoFactorEnabled = false,
                            UserName = "jorge@test.com"
                        },
                        new
                        {
                            Id = "u-elena-1008",
                            AccessFailedCount = 0,
                            Ape_materno = "Ortiz",
                            Ape_paterno = "Castro",
                            ConcurrencyStamp = "0daf4433-68f8-4333-b76f-53659a640dc3",
                            Email = "elena@test.com",
                            EmailConfirmed = true,
                            FechaRegistro = new DateTime(2026, 3, 24, 11, 5, 28, 450, DateTimeKind.Utc).AddTicks(4335),
                            Fecha_naci = new DateTime(1993, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Foto_perfil = "/images/user-default.png",
                            LockoutEnabled = false,
                            Nombre = "Elena",
                            NormalizedEmail = "ELENA@TEST.COM",
                            NormalizedUserName = "ELENA@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENucWhZnfFnwTG3XwSe9ZOBoF3sk5AgciYQHosPGX5wsbI4M4lXjhMeIHn/83GaSxA==",
                            PhoneNumber = "71234568",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e45e68b2-a2ad-415b-9a31-5cd702c6d731",
                            TwoFactorEnabled = false,
                            UserName = "elena@test.com"
                        },
                        new
                        {
                            Id = "u-luis-1009",
                            AccessFailedCount = 0,
                            Ape_materno = "Blanco",
                            Ape_paterno = "Alvarez",
                            ConcurrencyStamp = "d22bdf34-daf9-4b27-8731-80ae4cb9879b",
                            Email = "luis@test.com",
                            EmailConfirmed = true,
                            FechaRegistro = new DateTime(2026, 3, 24, 11, 5, 28, 604, DateTimeKind.Utc).AddTicks(8793),
                            Fecha_naci = new DateTime(1989, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Foto_perfil = "/images/user-default.png",
                            LockoutEnabled = false,
                            Nombre = "Luis",
                            NormalizedEmail = "LUIS@TEST.COM",
                            NormalizedUserName = "LUIS@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKcLqdGZWnnZtO8uMiw39nT31JDQENBSUgCdn+EUFhP/aX1oYAOkgKBmhNvuE2Tckw==",
                            PhoneNumber = "71234569",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9ba2e4fb-e728-4e79-84bf-d0c20a976564",
                            TwoFactorEnabled = false,
                            UserName = "luis@test.com"
                        },
                        new
                        {
                            Id = "u-sofia-1010",
                            AccessFailedCount = 0,
                            Ape_materno = "Navarro",
                            Ape_paterno = "Jimenez",
                            ConcurrencyStamp = "56cdda5f-84a7-42e9-960a-b799c5df650b",
                            Email = "sofia@test.com",
                            EmailConfirmed = true,
                            FechaRegistro = new DateTime(2026, 3, 24, 11, 5, 28, 802, DateTimeKind.Utc).AddTicks(3663),
                            Fecha_naci = new DateTime(1996, 10, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Foto_perfil = "/images/user-default.png",
                            LockoutEnabled = false,
                            Nombre = "Sofia",
                            NormalizedEmail = "SOFIA@TEST.COM",
                            NormalizedUserName = "SOFIA@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEI1/nxsTMj6hMxG5icB0EvxLsRK673h8OxNgiNaMJUorpGFFFTJM5aTtKhXTKdkW3Q==",
                            PhoneNumber = "71234570",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "03b53215-6447-4d2e-9dab-6128113d35ae",
                            TwoFactorEnabled = false,
                            UserName = "sofia@test.com"
                        },
                        new
                        {
                            Id = "u-miguel-1011",
                            AccessFailedCount = 0,
                            Ape_materno = "Delgado",
                            Ape_paterno = "Moreno",
                            ConcurrencyStamp = "6e6def22-db9e-4600-840e-b33ee3538b23",
                            Email = "miguel@test.com",
                            EmailConfirmed = true,
                            FechaRegistro = new DateTime(2026, 3, 24, 11, 5, 28, 931, DateTimeKind.Utc).AddTicks(3562),
                            Fecha_naci = new DateTime(1987, 8, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Foto_perfil = "/images/user-default.png",
                            LockoutEnabled = false,
                            Nombre = "Miguel",
                            NormalizedEmail = "MIGUEL@TEST.COM",
                            NormalizedUserName = "MIGUEL@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHPM9NQw46LJzVoQ5cEQPJN+AsFydmm1bIVgvgLh4SwTwNnnLwE1+UERhgBs1fdSjg==",
                            PhoneNumber = "71234571",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b21d7246-cd4a-4032-82a4-9bcb442354ae",
                            TwoFactorEnabled = false,
                            UserName = "miguel@test.com"
                        },
                        new
                        {
                            Id = "u-laura-1012",
                            AccessFailedCount = 0,
                            Ape_materno = "Mendez",
                            Ape_paterno = "Ibañez",
                            ConcurrencyStamp = "a189b715-1174-4dbb-b11d-7b5da8db141f",
                            Email = "laura@test.com",
                            EmailConfirmed = true,
                            FechaRegistro = new DateTime(2026, 3, 24, 11, 5, 29, 54, DateTimeKind.Utc).AddTicks(5962),
                            Fecha_naci = new DateTime(1999, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Foto_perfil = "/images/user-default.png",
                            LockoutEnabled = false,
                            Nombre = "Laura",
                            NormalizedEmail = "LAURA@TEST.COM",
                            NormalizedUserName = "LAURA@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELUQwtj+x7Wul6CSdPAo6A84uuKaPFLQIWy0EAI6VtPB8rLV1Yzywge3X+w+NQjBNg==",
                            PhoneNumber = "71234572",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b6cb6c7a-fa0a-4d6d-bd95-8e6ff8a40c02",
                            TwoFactorEnabled = false,
                            UserName = "laura@test.com"
                        },
                        new
                        {
                            Id = "u-raul-1013",
                            AccessFailedCount = 0,
                            Ape_materno = "Serrano",
                            Ape_paterno = "Gil",
                            ConcurrencyStamp = "e7790c08-fe8f-42a9-8f9e-04aeb46560d1",
                            Email = "raul@test.com",
                            EmailConfirmed = true,
                            FechaRegistro = new DateTime(2026, 3, 24, 11, 5, 29, 187, DateTimeKind.Utc).AddTicks(6486),
                            Fecha_naci = new DateTime(1994, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Foto_perfil = "/images/user-default.png",
                            LockoutEnabled = false,
                            Nombre = "Raul",
                            NormalizedEmail = "RAUL@TEST.COM",
                            NormalizedUserName = "RAUL@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECS72g6OCDHRP/zesho3SpEmAr3HXmuHjLC6dkid5HyXSUeF3kgFSZPN/yIENWYkwA==",
                            PhoneNumber = "71234573",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ee24cf5d-07a5-4327-9b98-3b0654406968",
                            TwoFactorEnabled = false,
                            UserName = "raul@test.com"
                        },
                        new
                        {
                            Id = "u-marta-1014",
                            AccessFailedCount = 0,
                            Ape_materno = "Aguilar",
                            Ape_paterno = "Ferrer",
                            ConcurrencyStamp = "838b4fde-b844-4c22-ae03-ea81ede486d4",
                            Email = "marta@test.com",
                            EmailConfirmed = true,
                            FechaRegistro = new DateTime(2026, 3, 24, 11, 5, 29, 301, DateTimeKind.Utc).AddTicks(7109),
                            Fecha_naci = new DateTime(1992, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Foto_perfil = "/images/user-default.png",
                            LockoutEnabled = false,
                            Nombre = "Marta",
                            NormalizedEmail = "MARTA@TEST.COM",
                            NormalizedUserName = "MARTA@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHBoB558J+sxSo0W45zGZCixlcuZElaO3lO7EZMdoP+4gMX5nHJjKOPe25tRbnVCMA==",
                            PhoneNumber = "71234574",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6d2024ae-38b2-4036-89be-94945cadf175",
                            TwoFactorEnabled = false,
                            UserName = "marta@test.com"
                        },
                        new
                        {
                            Id = "u-david-1015",
                            AccessFailedCount = 0,
                            Ape_materno = "Hidalgo",
                            Ape_paterno = "Cano",
                            ConcurrencyStamp = "61e0a2a1-af4b-4d54-b582-19e2b53282a2",
                            Email = "david@test.com",
                            EmailConfirmed = true,
                            FechaRegistro = new DateTime(2026, 3, 24, 11, 5, 29, 420, DateTimeKind.Utc).AddTicks(2683),
                            Fecha_naci = new DateTime(1986, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Foto_perfil = "/images/user-default.png",
                            LockoutEnabled = false,
                            Nombre = "David",
                            NormalizedEmail = "DAVID@TEST.COM",
                            NormalizedUserName = "DAVID@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPNx+lkBzOEsniNklqdWrhOKBjfJ5Ne1vENNAIeMc84iXrU3h1gZEQA0C0/isGVWqw==",
                            PhoneNumber = "71234575",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "629f59ee-ca42-4c18-b7d5-f2a681d84fb4",
                            TwoFactorEnabled = false,
                            UserName = "david@test.com"
                        },
                        new
                        {
                            Id = "u-claudia-1016",
                            AccessFailedCount = 0,
                            Ape_materno = "Pascual",
                            Ape_paterno = "Vidal",
                            ConcurrencyStamp = "39dd4397-1dc7-4751-99e7-6f0ccf97c89e",
                            Email = "claudia@test.com",
                            EmailConfirmed = true,
                            FechaRegistro = new DateTime(2026, 3, 24, 11, 5, 29, 538, DateTimeKind.Utc).AddTicks(3952),
                            Fecha_naci = new DateTime(1998, 12, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Foto_perfil = "/images/user-default.png",
                            LockoutEnabled = false,
                            Nombre = "Claudia",
                            NormalizedEmail = "CLAUDIA@TEST.COM",
                            NormalizedUserName = "CLAUDIA@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHKpiUtKqsqI7Uq2tyx+kDbrXWTxcBr7tX4hDxMRnOOCx7GwjrB0ZN+Mpeocoj5Upw==",
                            PhoneNumber = "71234576",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "50422bc9-542d-42fb-acf7-7aa30efb3389",
                            TwoFactorEnabled = false,
                            UserName = "claudia@test.com"
                        },
                        new
                        {
                            Id = "u-oscar-1017",
                            AccessFailedCount = 0,
                            Ape_materno = "Campos",
                            Ape_paterno = "Gallego",
                            ConcurrencyStamp = "a88b4080-5736-4d26-8830-7a7aee2cdc45",
                            Email = "oscar@test.com",
                            EmailConfirmed = true,
                            FechaRegistro = new DateTime(2026, 3, 24, 11, 5, 29, 656, DateTimeKind.Utc).AddTicks(6872),
                            Fecha_naci = new DateTime(1990, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Foto_perfil = "/images/user-default.png",
                            LockoutEnabled = false,
                            Nombre = "Oscar",
                            NormalizedEmail = "OSCAR@TEST.COM",
                            NormalizedUserName = "OSCAR@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEA0ea1w/1Qxaf/b9FtPEXVU4eh6I2EcPrjLM4M4F08f3B0O26oefKOtqc/yGhPJPtQ==",
                            PhoneNumber = "71234577",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f37e95f1-f0db-4bc0-834e-deffb1736c44",
                            TwoFactorEnabled = false,
                            UserName = "oscar@test.com"
                        },
                        new
                        {
                            Id = "u-silvia-1018",
                            AccessFailedCount = 0,
                            Ape_materno = "Fuentes",
                            Ape_paterno = "Peña",
                            ConcurrencyStamp = "4b7cccea-7acf-47ae-a6be-20d017e37b80",
                            Email = "silvia@test.com",
                            EmailConfirmed = true,
                            FechaRegistro = new DateTime(2026, 3, 24, 11, 5, 30, 70, DateTimeKind.Utc).AddTicks(4636),
                            Fecha_naci = new DateTime(1995, 8, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Foto_perfil = "/images/user-default.png",
                            LockoutEnabled = false,
                            Nombre = "Silvia",
                            NormalizedEmail = "SILVIA@TEST.COM",
                            NormalizedUserName = "SILVIA@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIA/yQF2+pqGIDdNArhNQY/0zTbqYLJMG2eqw7I+F6nEgkgVIwVAgnrpAJqZl9r39w==",
                            PhoneNumber = "71234578",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "39d57c31-e2b8-4b70-99c2-1f6b5aac524b",
                            TwoFactorEnabled = false,
                            UserName = "silvia@test.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AgendaApi.Models.Agenda", b =>
                {
                    b.HasOne("AgendaApi.Models.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("Id_evento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgendaApi.Models.Usuario", "Usuario")
                        .WithMany("MisSuscripciones")
                        .HasForeignKey("Id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AgendaApi.Models.Evento", b =>
                {
                    b.HasOne("AgendaApi.Models.Usuario", "Creador")
                        .WithMany("MisEventos")
                        .HasForeignKey("Id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creador");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AgendaApi.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AgendaApi.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgendaApi.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AgendaApi.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgendaApi.Models.Usuario", b =>
                {
                    b.Navigation("MisEventos");

                    b.Navigation("MisSuscripciones");
                });
#pragma warning restore 612, 618
        }
    }
}
