// <auto-generated />
using System;
using AgendaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgendaApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgendaApi.Models.Agenda", b =>
                {
                    b.Property<string>("Id_usuario")
                        .HasColumnType("text");

                    b.Property<int>("Id_evento")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id_usuario", "Id_evento");

                    b.HasIndex("Id_evento");

                    b.ToTable("Agendas", (string)null);

                    b.HasData(
                        new
                        {
                            Id_usuario = "u-lizeth-60171101",
                            Id_evento = 1,
                            Estado = "Aceptado",
                            FechaAsignacion = new DateTime(2026, 3, 23, 0, 32, 40, 336, DateTimeKind.Utc).AddTicks(2733)
                        },
                        new
                        {
                            Id_usuario = "u-lizeth-60171101",
                            Id_evento = 2,
                            Estado = "Pendiente",
                            FechaAsignacion = new DateTime(2026, 3, 23, 0, 32, 40, 336, DateTimeKind.Utc).AddTicks(3334)
                        },
                        new
                        {
                            Id_usuario = "u-eddy-67015593",
                            Id_evento = 3,
                            Estado = "Aceptado",
                            FechaAsignacion = new DateTime(2026, 3, 23, 0, 32, 40, 336, DateTimeKind.Utc).AddTicks(3334)
                        },
                        new
                        {
                            Id_usuario = "u-eddy-67015593",
                            Id_evento = 4,
                            Estado = "Pendiente",
                            FechaAsignacion = new DateTime(2026, 3, 23, 0, 32, 40, 336, DateTimeKind.Utc).AddTicks(3335)
                        });
                });

            modelBuilder.Entity("AgendaApi.Models.Evento", b =>
                {
                    b.Property<int>("Id_evento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_evento"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha_finalizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fecha_inicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Hora_finalizacion")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("Hora_inicio")
                        .HasColumnType("interval");

                    b.Property<string>("Id_usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Imagen")
                        .HasColumnType("text");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<string>("Lugar")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_evento");

                    b.HasIndex("Id_usuario");

                    b.ToTable("Eventos", (string)null);

                    b.HasData(
                        new
                        {
                            Id_evento = 1,
                            Fecha_finalizacion = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fecha_inicio = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hora_finalizacion = new TimeSpan(0, 11, 0, 0, 0),
                            Hora_inicio = new TimeSpan(0, 9, 0, 0, 0),
                            Id_usuario = "u-eddy-67015593",
                            Lugar = "Oficina Central",
                            Nombre = "Reunión de Proyecto IATEC",
                            Tipo = "Compartido"
                        },
                        new
                        {
                            Id_evento = 2,
                            Fecha_finalizacion = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fecha_inicio = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hora_finalizacion = new TimeSpan(0, 21, 0, 0, 0),
                            Hora_inicio = new TimeSpan(0, 19, 0, 0, 0),
                            Id_usuario = "u-eddy-67015593",
                            Lugar = "Cancha 5",
                            Nombre = "Partido de Futbol",
                            Tipo = "Exclusivo"
                        },
                        new
                        {
                            Id_evento = 3,
                            Fecha_finalizacion = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fecha_inicio = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hora_finalizacion = new TimeSpan(0, 16, 0, 0, 0),
                            Hora_inicio = new TimeSpan(0, 14, 0, 0, 0),
                            Id_usuario = "u-lizeth-60171101",
                            Lugar = "Auditorio",
                            Nombre = "Presentación de Tesis",
                            Tipo = "Compartido"
                        },
                        new
                        {
                            Id_evento = 4,
                            Fecha_finalizacion = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fecha_inicio = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hora_finalizacion = new TimeSpan(0, 11, 0, 0, 0),
                            Hora_inicio = new TimeSpan(0, 10, 0, 0, 0),
                            Id_usuario = "u-lizeth-60171101",
                            Lugar = "Clínica Dental",
                            Nombre = "Cita Dental",
                            Tipo = "Exclusivo"
                        });
                });

            modelBuilder.Entity("AgendaApi.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Ape_materno")
                        .HasColumnType("text");

                    b.Property<string>("Ape_paterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fecha_naci")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Foto_perfil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "u-eddy-67015593",
                            AccessFailedCount = 0,
                            Ape_materno = "Condori",
                            Ape_paterno = "Mamani",
                            ConcurrencyStamp = "450d9fef-ec72-4dce-8eab-909e7bfd68f7",
                            Email = "eddy@test.com",
                            EmailConfirmed = true,
                            FechaRegistro = new DateTime(2026, 3, 23, 0, 32, 40, 338, DateTimeKind.Utc).AddTicks(3289),
                            Fecha_naci = new DateTime(1995, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Foto_perfil = "/images/user-default.png",
                            LockoutEnabled = false,
                            Nombre = "Eddy",
                            NormalizedEmail = "EDDY@TEST.COM",
                            NormalizedUserName = "EDDY@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGGv/3MgAV5hR8t0w6pC4wjoJJLCp0sKFhDLpPvh8gMi0F3AnWAE3RQMgJvYU/vMEg==",
                            PhoneNumber = "67015593",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "67811d61-3b3a-4313-bf3a-1f1191c14217",
                            TwoFactorEnabled = false,
                            UserName = "eddy@test.com"
                        },
                        new
                        {
                            Id = "u-lizeth-60171101",
                            AccessFailedCount = 0,
                            Ape_materno = "Fernandez",
                            Ape_paterno = "Calle",
                            ConcurrencyStamp = "03854ea1-f3c3-45ae-957f-da8ec5093c2b",
                            Email = "lizeth@test.com",
                            EmailConfirmed = true,
                            FechaRegistro = new DateTime(2026, 3, 23, 0, 32, 40, 377, DateTimeKind.Utc).AddTicks(4740),
                            Fecha_naci = new DateTime(1998, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Foto_perfil = "/images/user-default.png",
                            LockoutEnabled = false,
                            Nombre = "Lizeth Aidee",
                            NormalizedEmail = "LIZETH@TEST.COM",
                            NormalizedUserName = "LIZETH@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHuqdkg/Uxl0a7b9Rh0y8Dq0OWxA/31bJuSHeSZyd/PEy+qznZNCn70ttNasmQBgLA==",
                            PhoneNumber = "60171101",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4f72a217-fc99-434c-9a18-4c6242f1f811",
                            TwoFactorEnabled = false,
                            UserName = "lizeth@test.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AgendaApi.Models.Agenda", b =>
                {
                    b.HasOne("AgendaApi.Models.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("Id_evento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgendaApi.Models.Usuario", "Usuario")
                        .WithMany("MisSuscripciones")
                        .HasForeignKey("Id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AgendaApi.Models.Evento", b =>
                {
                    b.HasOne("AgendaApi.Models.Usuario", "Creador")
                        .WithMany("MisEventos")
                        .HasForeignKey("Id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creador");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AgendaApi.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AgendaApi.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgendaApi.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AgendaApi.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgendaApi.Models.Usuario", b =>
                {
                    b.Navigation("MisEventos");

                    b.Navigation("MisSuscripciones");
                });
#pragma warning restore 612, 618
        }
    }
}
